version: '3.9'
services:
  ml-api:
    build: .
    container_name: cifar10_api
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - ENV=prod

  ui:
    build: .
    container_name: cifar10_ui
    command: streamlit run ui/streamlit_app.py --server.port 8501 --server.headless true
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./logs:/app/logs

